[package]
name = "lineselect"
version = "0.1.0"
edition = "2021"
description = "Interactive Line Selector"
authors = ["Gilson Urbano"]
readme = "README.md"
license-file = "LICENSE"
repository = "https://github.com/urbanogilson/lineselect"

[dependencies]
clap = "4.3.11"
colored = "2.0.4"
dialoguer = "0.10.4"
